#!/usr/bin/perl

use strict;
use warnings;

use constant CPANEL_WHM_URL => 'ssh://git@{host}:7999/cpanel/cpanel-whm.git';

my $major_version = get_major_version();

if ( !$ENV{'GIT_HOST'} ) {
    die "Please set the GIT_HOST env variable";
}

if ( !$ENV{'SSH_AUTH_SOCK'} ) {
    die "Please connect with ssh -A";
}

my $git_host   = $ENV{'GIT_HOST'};
my $git_target = CPANEL_WHM_URL =~ s/\{host\}/$git_host/gr;

update_bashrc();
ensure_skip_parent_check();

system("git archive --format=tar --remote=$git_target $major_version:build-tools bootstrap_sandbox | tar -Opvx > ~/bootstrap_sandbox && chmod +x ~/bootstrap_sandbox && ~/bootstrap_sandbox $major_version && rm ~/bootstrap_sandbox");

sub get_file_contents_if_exists {
    my ($file) = @_;
    if ( open( my $fh, '<', $file ) ) {
        local $/;
        return readline($fh);
    }
    return '';
}

sub ensure_skip_parent_check {
    print "Ensuring parent check...\n";
    if ( get_file_contents_if_exists('/var/cpanel/cpanel.config') =~ m{skipparentcheck=1} ) {
        return;
    }
    append_file( '/var/cpanel/cpanel.config', "\nskipparentcheck=1\n" );
    return;
}

sub update_bashrc {
    print "Updating /root/.bashrc...\n";
    if ( get_file_contents_if_exists('/root/.bashrc') =~ m{build-tools} ) {
        return;
    }
    append_file( '/root/.bashrc', qq{\n\nexport PATH="/usr/local/cpanel/3rdparty/bin:/usr/local/cpanel/build-tools:/usr/local/sandbox-utils/bin:/usr/local/cpanel/t/qa/bin:\$PATH"\n\n} );
    chmod( 0700, "/root/.bashrc" );
    return;
}

sub append_file {
    my ( $file, $data ) = @_;
    open( my $fh, '>>', $file ) or die "Failed to open $file: $!";
    print {$fh} $data;
}

sub get_major_version {
    my $cpanel_version = `/usr/local/cpanel/cpanel -V`;
    chomp $cpanel_version;

    my $major_version = int( ( split( m{\s+}, $cpanel_version ) )[0] );

    if ( $major_version % 2 != 0 ) {
        $major_version++;
    }

    return $major_version;
}
